import Footer from '@/components/footer';
import Header from '@/components/header';
import './globals.css'
import 'swiper/css';
import Head from 'next/head';
import NextTopLoader from 'nextjs-toploader';


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

    const paths = [
        {
            name: "Услуги",
            link: "/pricing",
        },
        {
            name: "Клиника",
            link: "/clinic",
        },
        {
            name: "Врачи",
            link: "/doctors",
        },
        {
            name: "Отзывы",
            link: "/reviews",
        },
        {
            name: "Работы",
            link: "/works",
        },
        {
            name: "Вопрос-ответ",
            link: "/faq",
        },
        {
            name: "Контакты",
            link: "/#contacts",
        },
    ]
    return (
        <html lang="en">
            <Head>
                <meta name="viewport" content="viewport-fit=cover" />
            </Head>
            <body>
                <NextTopLoader
                    color="#D72642"
                    shadow="0 0 5px #BB132E"
                    showSpinner={false}
                />
                <Header paths={paths} />
                {children}
                <Footer paths={paths} />
            </body>

        </html>
    )
}
